genes:
  - E
  - NS1
  - NS3

trimmed_dir: "results/alignments/trimmed"
model_dir: "results/model_selection"
individual_tree_dir: "results/trees/individual"
concatenated_dir: "results/concatenated"
coalescent_dir: "results/trees/coalescent"
comparison_dir: "results/tree_comparison"
visualization_dir: "results/visualizations"
report_dir: "results/report"

bootstrap: 100
threads_iqtree: 4